# Unique identifiers from your SonarCloud dashboard
sonar.organization=ramana399654-ux
sonar.projectKey=ramana399654-ux_django-nginx-k8s-pipeline
sonar.projectName=django-nginx-k8s-pipeline

# Tell Sonar to scan your backend folder where your Python app lives
sonar.sources=backend
# Tell Sonar where your unit tests live so it can track coverage metrics
sonar.tests=backend
sonar.test.inclusions=backend/test_app.py

# Encoding of the source code
sonar.sourceEncoding=UTF-8
