server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://django-backend-service:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 200 'NGINX Reverse Proxy is Online - Version 1.1.0\n';
        add_header Content-Type text/plain;
    }
}
